version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: commodity_postgres
    environment:
      POSTGRES_USER: kaixin
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: commodity_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: