services:
  postgres:
    image: postgres:16
    container_name: commodity_postgres
    environment:
      POSTGRES_USER: kaixin
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: commodity_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pipeline:
    build: .
    container_name: commodity_pipeline
    depends_on:
      - postgres
    environment:
      DB_HOST: commodity_postgres
      DB_PORT: 5432
      DB_NAME: commodity_data
      DB_USER: kaixin
      DB_PASSWORD: localdevpassword

volumes:
  pgdata: